name: Build And Push to Staging
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Deployer
        run: pip install revampdeployer asyncssh 
      - name: Deploy 
        working-directory: ./util/deployer/
        run: revampdeployer staging
